import assert from 'node:assert/strict';
import test from 'node:test';
import { classifyRawCapture } from '../capture-quality';
import { saveRawJob } from '../db';

test('rejects non-job page captures', () => {
  assert.deepEqual(classifyRawCapture('City of Abbotsford', 'We apologize for the inconvenience... activity and behavior on this site made us think that you are a bot.'), { valid: false, issue: 'bot_challenge' });
  assert.deepEqual(classifyRawCapture('Government of Canada', '404 Not Found\nCode: NoSuchKey\nThe specified key does not exist.'), { valid: false, issue: 'error_page' });
  assert.deepEqual(classifyRawCapture('University of Toronto', 'Skip to main contentLoadingFollow UsPrivacy Statement'), { valid: false, issue: 'unrendered' });
  assert.deepEqual(classifyRawCapture('Government of Canada', 'Join Our Talent Community Current Openings (1 of 1) Search Protection Officer Powered by REQUIREMENTS'), { valid: false, issue: 'generic_portal' });
  assert.deepEqual(classifyRawCapture('Metrolinx', 'Talent Acquisition Consultant\nWork Summary\nThis summary is generated by AI Assist.\nCandidate profile information is available.'), { valid: true });
});

test('does not reject a real posting that is open until filled', () => {
  const rawText = 'Position: Recreation Facilities Attendant\nPosting will remain open until the position has been filled.\nDuties include facility operations and customer service.';
  assert.deepEqual(classifyRawCapture('City of Richmond', rawText), { valid: true });
});

test('saveRawJob rejects a non-job capture before creating a shell', async () => {
  const statements: Array<{ sql: string; args?: unknown[] }> = [];
  const client = {
    batch: async (queries: Array<{ sql: string; args?: unknown[] }>) => {
      statements.push(...queries);
      return [];
    },
  };

  const saved = await saveRawJob(client as never, {
    id: 'blocked-job',
    url: 'https://example.com/blocked-job',
    source: 'City of Abbotsford',
    title: 'View Job Details',
    raw_text: 'Confirm you are not a robot',
  });

  assert.equal(saved, false);
  assert.equal(statements.some(statement => /INSERT INTO raw_jobs/i.test(statement.sql)), false);
  assert.equal(statements.some(statement => /INSERT INTO jobs/i.test(statement.sql)), false);
});
