import { createClient } from '@libsql/client';
import dotenv from 'dotenv';

dotenv.config({ quiet: true });
const APPLY = process.argv.includes('--apply');

type Patch = {
  id: string;
  fields: Record<string, string | number | null>;
  description: string;
  rawPostedAt?: string;
};

const j = (values: string[]) => JSON.stringify(values);
const descriptions: Record<string, string> = {
  'J0626-0959': [
    '## Overview',
    'The Associate Director, Sustainable Transportation Transit Research develops and executes externally funded applied research and innovation programs in transportation and transit, including work funded through the NSERC Mobilize Grant. The role builds partnerships and manages approved projects.',
    '',
    '## Responsibilities',
    '- Provide applied research leadership and maintain knowledge of research methodologies, processes and ethics.',
    '- Maintain relationships with industry associations and develop strategic partnerships.',
    '- Manage major programs through initiation, planning, execution, monitoring, control and closeout.',
    '- Identify partnership and funding opportunities and develop new research projects.',
    '- Monitor project performance, progress, risk, variance and cost control.',
    '- Manage contracts for faculty, students, consultants, contractors, vendors and suppliers.',
    '- Analyze stakeholders, plan engagement and manage relationships.',
    '- Manage Centennial bus design innovation research with the TTC and Amalgamated Transit Workers Union.',
    '',
    '## Qualifications',
    '- Knowledge of transportation innovation and applied research practice.',
    '- Knowledge of research laws and regulations, including the Tri-Council Policy Statement on Research Ethics.',
    '- Strong proposal-writing, presentation and communication skills.',
    '- Sound decision-making, relationship-building, team-leadership and organizational skills.',
    '- Ability to work effectively in a highly diverse environment.',
  ].join('\n'),
  '461-en_US': [
    '## Overview',
    'This position provides analysis, recommendations and support for Recreation systems, ensuring optimum functionality and configuration while protecting system integrity.',
    '',
    '## Responsibilities',
    '- Determine operational objectives, gather requirements, identify problems and recommend solutions.',
    '- Consult with functional and management staff to document procedures, problems and system issues.',
    '- Analyze data, provide statistical overviews and troubleshoot emerging issues.',
    '- Implement process improvements and assist with system upgrades, testing and continuous improvement.',
    '- Act as a subject-matter expert, respond to user inquiries and support system maximization.',
    '- Conduct reporting and system audits to maintain system integrity.',
    '- Configure system changes involving fees, memberships, programs, point of sale, equipment, accounting, subsidies and reporting.',
    '- Maintain documentation, reference guides and training materials.',
    '- Participate in project teams and liaise with IT and third-party vendors.',
    '',
    '## Qualifications',
    '- Strong analytical, problem-solving, organizational and communication skills.',
    '- Ability to manage competing tasks, support users and work with functional teams and vendors.',
    '',
    '## Nice to Have',
    '- PerfectMind software experience.',
    '- Project management or experience coordinating the work of others.',
  ].join('\n'),
  'a4a12ab390a6': [
    '## Overview',
    'The Food & Beverage Coordinator supports food and beverage operations for members, guests and visitors at the Wayne Gretzky Sports Centre. The Coordinator provides customer service and leads staff while maintaining safe, efficient and professional operations.',
    '',
    '## Responsibilities',
    '- Coordinate day-to-day food and beverage operations under established policies and procedures.',
    '- Provide customer service and support a positive dining experience.',
    '- Coordinate Food and Beverage Attendant staff and reinforce service standards.',
    '- Develop daily specials and assist with menu planning and updates.',
    '- Monitor inventory, control waste, order products and coordinate invoices.',
    '- Assist with staff scheduling and support service during peak periods.',
    '- Support safe food preparation and service.',
    '- Maintain a clean, organized and safe work environment.',
    '- Train and onboard new staff members.',
    '- Perform other related duties as assigned.',
    '',
    '## Qualifications',
    '- Strong organization, multitasking and time-management skills.',
    '- Commitment to courteous, respectful and professional service.',
    '- Ability to maintain workplace safety and adhere to deadlines.',
    '- Ability to stand for long periods and perform medium physical work.',
  ].join('\n'),
  'psft_314955': [
    '## Overview',
    'The CPIC Information Specialist creates, maintains and verifies records submitted to the Canadian Police Information Centre on behalf of Calgary Police Service.',
    '',
    '## Responsibilities',
    '- Respond to requests by radio, telephone and messaging.',
    '- Research, organize and distribute sensitive information from multiple databases.',
    '- Prepare Prosecutor Information Packages and Field Officer Release documents.',
    '- Coordinate responses to CPIC requests from police and law-enforcement agencies.',
    '- Enter, update and remove records in the National CPIC database according to policy.',
    '- Maintain warrants, court orders, release documents and occurrence reports.',
    '- Complete validations, purge reports and warrant-recall lists to keep records current.',
    '',
    '## Qualifications',
    '- Ability to type at least 50 words per minute.',
    '- Emotional intelligence, sound judgment and respectful working relationships.',
    '- Applicants will be tested for appropriate skills.',
    '',
    '## Nice to Have',
    '- CPIC experience.',
    '- Experience with Sentry (Niche) or the Justice On-Line Information Network.',
  ].join('\n'),
  'phenom_55451': [
    '## Overview',
    'The Apprentice Heavy Equipment Technician trains in heavy equipment maintenance and repair while progressing through the City’s transit fleet maintenance apprenticeship program.',
    '',
    '## Responsibilities',
    '- Assist Journeypersons with inspections, preventative maintenance, repairs and overhauls.',
    '- Complete assigned work as skills progress through the apprenticeship.',
    '- Enter maintenance information into the computerized fleet-management system.',
    '- Follow manufacturer, shop and engineering instructions.',
    '- Diagnose systems using scanning tools, software and traditional methods.',
    '- Communicate with shop personnel and troubleshoot bus-fleet issues.',
    '- Follow safety standards and perform other related duties.',
    '',
    '## Qualifications',
    '- Acceptance into the apprenticeship program and ability to maintain passing grades.',
    '- Experience in an operational or vehicle-maintenance environment.',
    '- Ability to pass a job-related physical abilities evaluation.',
    '- Ability to apply trade knowledge to diagnose equipment malfunctions.',
    '- Strong problem-solving and interpersonal skills, willingness to learn and adaptability.',
    '',
    '## Nice to Have',
    '- AssetWorks M5 experience.',
  ].join('\n'),
  '1002-en_US': [
    '## Overview',
    'The Manager of Cemeteries leads the operation of seven cemetery properties and the Dedication Centre, including cemetery services, burials, maintenance, memorialization, legislative compliance, financial administration, budgeting and service planning.',
    '',
    '## Responsibilities',
    '- Lead process improvements, procedures, workflows and service standards for cemetery operations.',
    '- Oversee memorial documentation, cemetery records, databases, maps and interment-rights records.',
    '- Supervise cemetery staff, including hiring, orientation, training and performance management.',
    '- Direct payroll, accounts receivable, accounts payable and bank deposits.',
    '- Coordinate system updates and resolve or escalate technical issues.',
    '- Ensure compliance with occupational health and safety requirements.',
    '- Prepare reports, statistics, financial information and regulatory submissions.',
    '- Lead capital planning and asset management for cemetery infrastructure and equipment.',
    '- Coordinate reservations, transfers, refunds, trust-fund entries and annual reports.',
    '- Meet with families, cultural leaders and community organizations about cemetery services.',
    '- Coordinate Dedication Centre bookings and cemetery events.',
    '- Respond to escalated inquiries and perform operational duties when required.',
    '',
    '## Qualifications',
    '- Knowledge of cemetery operations, the Funeral, Burial and Cremation Services Act, AODA, OHSA, municipal by-laws and related legislation.',
    '- Leadership, financial, communication, problem-solving and organizational skills.',
    '- Ability to respond professionally to emotionally charged situations and apply legislation.',
    '- Ability to evaluate market trends and business practices for improvements.',
    '- Reliable with a good attitude and employment record.',
  ].join('\n'),
  '604824117': [
    '## Overview',
    'The Specialist, Job Analyst leads job analysis and evaluation processes, supports organizational design analysis and provides recommendations related to organizational structures, policy, procedure and pay equity.',
    '',
    '## Responsibilities',
    '- Gather, document and analyze job information and administer job evaluation for non-union roles.',
    '- Advise managers on new and existing positions.',
    '- Support confidential organizational-design initiatives.',
    '- Conduct research and prepare reports, statistics and recommendations.',
    '- Develop and maintain organizational charts.',
    '- Prepare pay-equity documentation and monitor related legislation and policy.',
    '- Build partnerships across the corporation and with external municipal counterparts.',
    '- Maintain job-evaluation systems and processes.',
    '- Track performance measures using data collection and analytics.',
    '- Support anti-racism, human rights and health-and-safety objectives.',
    '- Participate on committees and special projects.',
    '',
    '## Qualifications',
    '- Knowledge of organizational design, job evaluation, pay equity and job analysis.',
    '- Effective interpersonal, customer-service, conflict-resolution, report-writing and problem-solving skills.',
    '- Ability to plan, prioritize, manage time, analyze data and present findings.',
    '- Knowledge of project or change management, performance measurement and policy development.',
    '- Ability to support the implementation and maintenance of HR systems and databases.',
  ].join('\n'),
  'adp_4729': [
    '## Overview',
    'The Specialty Fitness Instructor I plans, organizes, instructs and leads fitness classes for participants of different ages and abilities at Thornhill Community Centre and Armadale Community Centre.',
    '',
    '## Responsibilities',
    '- Lead and supervise exercise sessions in assigned fitness areas.',
    '- Instruct participants in fitness activities, exercise methods, breathing techniques and progress monitoring.',
    '- Adjust program content to participant abilities and conduct classes as scheduled.',
    '- Plan routines, choose music and set up, monitor and store equipment.',
    '- Maintain attendance records and confirm participant readiness.',
    '- Communicate program changes, distribute handouts and evaluations and answer questions.',
    '- Report customer-service issues and keep facilities, equipment and supplies safe and ready.',
    '',
    '## Qualifications',
    '- Minimum age of 16 at the start of employment.',
    '- Ability to work effectively with varied clients and fitness levels.',
    '- Ability to follow and enforce safety procedures.',
    '- Strong communication, leadership, customer-service and interpersonal skills.',
    '- Knowledge of fitness, wellness, training principles, fitness theory and workout components.',
  ].join('\n'),
  '1291362047': [
    '## Overview',
    'The Customer Service Agent provides information and customer service for municipal and provincial services, programs, policies, procedures, permits and fee structures through ServiceOttawa Centres and multiple service channels.',
    '',
    '## Responsibilities',
    '- Respond to inquiries from the public, elected officials, internal staff and government agencies in person, online, by email and by phone.',
    '- Provide accurate information while minimizing unnecessary referrals and ensuring follow-up.',
    '- Determine the course of action for parking-ticket resolution under First Attendance Facility procedures.',
    '- Work according to corporate and departmental policies, legislation, service standards and quality requirements.',
    '',
    '## Qualifications',
    '- Knowledge of customer-service delivery and complaint-resolution practices.',
    '- Knowledge of provincial legislation, regulations, corporate policies and procedures.',
    '- Knowledge of applicable health-and-safety legislation.',
    '- Strong interpersonal, communication, writing, organizational and multitasking skills.',
    '- Ability to exercise sound judgment, work independently and work as part of a team.',
    '- Punctual, reliable, flexible and adaptable.',
    '',
    '## Nice to Have',
    '- Post-secondary education or training related to customer service.',
    '- Knowledge of City of Ottawa organizational structure, services and personnel.',
  ].join('\n'),
  '2626': [
    '## Overview',
    'The Arena Labourer performs general maintenance and operational duties for the safe operation of community centres, marinas and arenas, including custodial work, equipment operations, repairs, events, security and ice maintenance.',
    '',
    '## Responsibilities',
    '- Maintain arena equipment such as ice resurfacers, ice edgers and furnaces and be familiar with sprinkler and alarm systems.',
    '- Maintain building cleanliness and sanitation in public and work areas.',
    '- Maintain safe work areas, vehicles, equipment and storage areas.',
    '- Collect garbage and recycling and perform groundskeeping and general maintenance.',
    '- Operate ice resurfacers and assist with equipment repairs.',
    '- Set up and tear down community events and fill in for crossing guards when required.',
    '- Follow occupational health and safety legislation, best practices and City procedures.',
    '',
    '## Qualifications',
    '- Highly developed professionalism, tact and diplomacy.',
    '- Respect for confidential and sensitive issues.',
    '- Strong telephone, public-relations, written and verbal communication skills.',
    '- Effective problem-solving and interpersonal skills.',
    '- Ability to perform the physical demands of the position.',
    '',
    '## Nice to Have',
    '- English and French communication ability.',
    '- Basic First Aid, CPR and AED certificate.',
    '- Propane-handling training and experience.',
    '- Special-events or municipal experience.',
  ].join('\n'),
};

const patches: Patch[] = [
  { id: 'J0626-0959', fields: { hours: '35 hours per week', availability: 'Weekdays' }, description: descriptions['J0626-0959'] },
  { id: '461-en_US', fields: { hours: '35 hours per week', education_requirements: j(['High school diploma plus a 3- to 4-year program in Computer Science, Business Management, Information Technology, Commerce, Technology or an equivalent field']), license_requirements: j(["Non-probationary valid Ontario Class G driver's licence"]), software_requirements: j(['Microsoft Office Suite', 'SharePoint', 'Office 365']), start_date: null }, description: descriptions['461-en_US'] },
  { id: 'a4a12ab390a6', fields: { employment_type: 'Part-time', hours: 'Up to 24 hours per week', software_requirements: j(['Restaurant point-of-sale systems']) }, description: descriptions['a4a12ab390a6'] },
  { id: 'psft_314955', fields: { duration: 'Up to 12 months (1 position); up to 6 months (3 positions)', hours: '40 hours per week', availability: 'Nights; Weekends; Shift work', software_requirements: j([]) }, description: descriptions['psft_314955'] },
  { id: 'phenom_55451', fields: { hours: '40 hours per week', availability: 'Shift work', education_requirements: j(['High school diploma (Grade 12) and ability to pass the Alberta Industry and Trade apprenticeship entrance exam']), license_requirements: j(["Valid Alberta Class 3 driver's licence or provincial equivalent", "City of Edmonton driver's permit"]), certification_requirements: j(['Truck and Transport Journeyperson certificate through the apprenticeship program', 'Commercial Vehicle Inspection Permit (CVIP) eligibility upon completion']), medical_requirements: j(['City medical examination']) }, description: descriptions['phenom_55451'] },
  { id: '1002-en_US', fields: { location: 'Kitchener, ON', hours: '35 hours per week', posted_at: '2026-07-30', start_date: null, required_skills: j([]), software_requirements: j(['Microsoft Office', 'Financial systems', 'Cemetery management software']) }, description: descriptions['1002-en_US'], rawPostedAt: '2026-07-30' },
  { id: '604824117', fields: { hours: '35 hours per week', availability: 'Weekdays' }, description: descriptions['604824117'] },
  { id: 'adp_4729', fields: { availability: 'Evenings; Weekends' }, description: descriptions['adp_4729'] },
  { id: '1291362047', fields: { location: 'Ottawa, ON', duration: 'Up to 1 year (temporary); permanent positions also available', hours: '35 hours per week' }, description: descriptions['1291362047'] },
  { id: '2626', fields: { employment_type: 'Seasonal', hours: 'Up to 40 hours per week', availability: 'Evenings; Weekends; Holidays; Shift work', license_requirements: j(["Valid Class G driver's licence and safe driving record"]), software_requirements: j(['Google Workspace', 'Dayforce']) }, description: descriptions['2626'] },
];

const allowed = new Set(['location', 'description', 'posted_at', 'employment_type', 'duration', 'hours', 'availability', 'required_skills', 'education_requirements', 'license_requirements', 'certification_requirements', 'software_requirements', 'medical_requirements', 'start_date']);

async function main() {
  const db = createClient({ url: process.env.TURSO_URL!, authToken: process.env.TURSO_AUTH_TOKEN! });
  for (const patch of patches) {
    const exists = await db.execute({ sql: 'SELECT id FROM job_details WHERE id = ?', args: [patch.id] });
    if (!exists.rows.length) throw new Error('Missing job_details row: ' + patch.id);
    console.log((APPLY ? 'Updating ' : 'Would update ') + patch.id);
    if (!APPLY) continue;
    const fields = { ...patch.fields, description: patch.description };
    const entries = Object.entries(fields).filter(([column]) => allowed.has(column));
    const assignments = entries.map(([column]) => column + ' = ?').join(', ');
    await db.execute({ sql: 'UPDATE job_details SET ' + assignments + ' WHERE id = ?', args: [...entries.map(([, value]) => value), patch.id] });
    if (patch.rawPostedAt) await db.execute({ sql: 'UPDATE raw_jobs SET posted_at = ? WHERE id = ?', args: [patch.rawPostedAt, patch.id] });
  }
  console.log((APPLY ? 'Applied ' : 'Dry run: ') + patches.length + ' full listing review patches.');
}

main().catch(error => { console.error(error); process.exit(1); });
