-- Civic Careers Postgres schema.
-- Apply this to a staging branch first. It intentionally keeps the existing
-- 0/1 integer flags and text-encoded JSON values so the first migration does
-- not also change application semantics.

CREATE TABLE IF NOT EXISTS jobs (
  id TEXT PRIMARY KEY,
  url TEXT,
  source TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  is_saved INTEGER NOT NULL DEFAULT 0,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scraped_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  verified_at TIMESTAMPTZ,
  public_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);

CREATE TABLE IF NOT EXISTS raw_jobs (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  source TEXT NOT NULL,
  raw_text TEXT NOT NULL DEFAULT '',
  title TEXT,
  first_seen_at TIMESTAMPTZ,
  scraped_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  parsed_at TIMESTAMPTZ,
  posted_at TEXT,
  application_url TEXT,
  pending_salary_text TEXT,
  pending_is_student INTEGER,
  pending_duration TEXT,
  pending_closing_date TEXT,
  pending_closing_date_status TEXT NOT NULL DEFAULT 'not_checked',
  pending_location TEXT
);

CREATE TABLE IF NOT EXISTS job_details (
  id TEXT PRIMARY KEY REFERENCES jobs(id),
  job_title TEXT,
  department TEXT,
  location TEXT,
  workplace_address TEXT,
  salary_range TEXT,
  description TEXT,
  closing_date TEXT,
  is_inventory INTEGER DEFAULT 0,
  listing_type TEXT DEFAULT 'regular',
  is_student INTEGER DEFAULT 0,
  salary_min NUMERIC,
  salary_max NUMERIC,
  salary_period TEXT,
  work_model TEXT,
  employment_type TEXT,
  duration TEXT,
  hours TEXT,
  availability TEXT,
  academic_role_type TEXT,
  academic_course TEXT,
  academic_workload TEXT,
  academic_office_hours TEXT,
  academic_supervisor TEXT,
  academic_appointment_type TEXT,
  academic_schedule TEXT,
  is_unionized INTEGER,
  union_name TEXT,
  benefits TEXT,
  required_skills TEXT,
  experience_requirements TEXT,
  education_requirements TEXT,
  license_requirements TEXT,
  vehicle_required INTEGER,
  language_requirements TEXT,
  security_check_required INTEGER,
  certification_requirements TEXT,
  software_requirements TEXT,
  medical_requirements TEXT,
  responsibility_tags TEXT,
  qualification_tags TEXT,
  posted_at TEXT,
  parser_version INTEGER,
  start_date TEXT,
  career_stage TEXT
);

CREATE TABLE IF NOT EXISTS parse_failures (
  id TEXT PRIMARY KEY,
  url TEXT NOT NULL,
  source TEXT NOT NULL,
  reason TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 1,
  last_failed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS source_scrape_status (
  source TEXT PRIMARY KEY,
  last_successful_scrape_at TIMESTAMPTZ,
  last_status TEXT NOT NULL DEFAULT 'success'
);

CREATE TABLE IF NOT EXISTS trial_source_results (
  source TEXT PRIMARY KEY,
  consecutive_successes INTEGER NOT NULL DEFAULT 0,
  last_status TEXT NOT NULL,
  last_job_count INTEGER NOT NULL DEFAULT 0,
  last_run_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS job_apply_clicks (
  job_id TEXT PRIMARY KEY,
  click_count INTEGER NOT NULL DEFAULT 0,
  last_clicked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS manual_review_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id TEXT NOT NULL,
  note TEXT NOT NULL,
  before_json TEXT NOT NULL,
  after_json TEXT NOT NULL,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS jobs_active_scraped_idx
  ON jobs (is_active, scraped_at DESC);
CREATE INDEX IF NOT EXISTS jobs_active_source_idx
  ON jobs (is_active, source);
CREATE INDEX IF NOT EXISTS jobs_verified_idx
  ON jobs (verified_at, is_active);
CREATE INDEX IF NOT EXISTS job_details_closing_date_idx
  ON job_details (closing_date);
CREATE INDEX IF NOT EXISTS raw_jobs_parsed_scraped_idx
  ON raw_jobs (parsed_at, scraped_at);
CREATE INDEX IF NOT EXISTS raw_jobs_source_scraped_idx
  ON raw_jobs (source, scraped_at DESC);
