export const COMPANY_TYPE_OPTIONS = [
  { value: 'library', label: 'Public libraries' },
  { value: 'transit', label: 'Transit agencies' },
  { value: 'higherEducation', label: 'Universities and colleges' },
  { value: 'municipal', label: 'Municipal governments' },
  { value: 'publicAgency', label: 'Public agencies' },
  { value: 'health', label: 'Health organizations' },
] as const;

export type CompanyType = typeof COMPANY_TYPE_OPTIONS[number]['value'];

// This is keyed by the scraper's exact source label. It is deliberately not
// inferred from words in company names, so an organization can have more than
// one stable type without changing when a name happens to contain "City" or
// "University".
export const COMPANY_TYPES: Record<string, CompanyType[]> = {
  'Government of Canada': ['publicAgency'],
  'Province of Ontario (OPS)': ['publicAgency'],
  'Province of Ontario': ['publicAgency'],
  'CMHC': ['publicAgency'],
  'Metrolinx': ['publicAgency', 'transit'],
  'VIA Rail Canada': ['transit'],
  'BC Transit': ['publicAgency', 'transit'],
  'TransLink': ['publicAgency', 'transit'],
  'Edmonton Transit': ['transit'],
  'TRCA': ['publicAgency'],
  'Infrastructure Ontario': ['publicAgency'],
  'CreateTO': ['publicAgency'],
  'Conservation Halton': ['publicAgency'],
  'Waterfront Toronto': ['publicAgency'],
  'TTC': ['transit', 'publicAgency'],
  'University of Windsor': ['higherEducation'],
  'Toronto District School Board': ['publicAgency'],
  'City of Barrie': ['municipal'],
  'City of Belleville': ['municipal'],
  'City of Brampton': ['municipal'],
  'City of Brantford': ['municipal'],
  'City of Brandon': ['municipal'],
  'City of Burlington': ['municipal'],
  'City of Cambridge': ['municipal'],
  'City of Cornwall': ['municipal'],
  'City of Guelph': ['municipal'],
  'City of Hamilton': ['municipal'],
  'City of Kitchener': ['municipal'],
  'City of Kingston': ['municipal'],
  'City of London': ['municipal'],
  'City of Markham': ['municipal'],
  'City of Niagara Falls': ['municipal'],
  'City of Oshawa': ['municipal'],
  'City of Peterborough': ['municipal'],
  'City of Richmond Hill': ['municipal'],
  'City of Sarnia': ['municipal'],
  'City of St. Catharines': ['municipal'],
  'City of St. Thomas': ['municipal'],
  'City of Thunder Bay': ['municipal'],
  'City of Toronto': ['municipal'],
  'City of Vancouver': ['municipal'],
  'City of Victoria': ['municipal'],
  'City of Vaughan': ['municipal'],
  'City of Waterloo': ['municipal'],
  'City of Welland': ['municipal'],
  'City of Windsor': ['municipal'],
  'City of Winnipeg': ['municipal'],
  'City of Edmonton': ['municipal'],
  'City of Ajax': ['municipal'],
  'Mississauga': ['municipal'],
  'City of Mississauga': ['municipal'],
  'City of Ottawa': ['municipal'],
  'City of Red Deer': ['municipal'],
  'Town of Ajax': ['municipal'],
  'Town of Aurora': ['municipal'],
  'Town of Caledon': ['municipal'],
  'Town of Milton': ['municipal'],
  'Town of Oakville': ['municipal'],
  'Town of Orangeville': ['municipal'],
  'Town of Smiths Falls': ['municipal'],
  'Town of Whitby': ['municipal'],
  'Municipality of Clarington': ['municipal'],
  'Northumberland County': ['municipal'],
  'Peel Region': ['municipal'],
  'Halton Region': ['municipal'],
  'Niagara Region': ['municipal'],
  'Region of Waterloo': ['municipal'],
  'York Region': ['municipal'],
  'University of Guelph': ['higherEducation'],
  'UBC': ['higherEducation'],
  'University of Ottawa': ['higherEducation'],
  'University of Toronto': ['higherEducation'],
  'University of Waterloo': ['higherEducation'],
  'York University': ['higherEducation'],
  'Algonquin College': ['higherEducation'],
  'Brock University': ['higherEducation'],
  'Carleton University': ['higherEducation'],
  'Centennial College': ['higherEducation'],
  'Durham College': ['higherEducation'],
  'Fanshawe College': ['higherEducation'],
  'George Brown College': ['higherEducation'],
  'Humber College': ['higherEducation'],
  'Mohawk College': ['higherEducation'],
  'OCAD University': ['higherEducation'],
  'Ontario Tech University': ['higherEducation'],
  "Queen's University": ['higherEducation'],
  'Seneca College': ['higherEducation'],
  'Sheridan College': ['higherEducation'],
  'Vaughan Public Library': ['library'],
  'Toronto Public Library': ['library'],
  'Edmonton Public Library': ['library'],
  'London Public Library': ['library'],
  'Oakville Public Library': ['library'],
  'Richmond Public Library': ['library'],
  'Pickering Public Library': ['library'],
  'Ontario Health': ['health', 'publicAgency'],
  'Ontario Health atHome': ['health', 'publicAgency'],
  'Public Health Ontario': ['health', 'publicAgency'],
  'Shared Health Manitoba': ['health', 'publicAgency'],
  'Manitoba Public Insurance': ['publicAgency'],
};

export function companyTypes(name: string): CompanyType[] {
  return COMPANY_TYPES[name] ?? [];
}

/**
 * Maintained official careers destinations keyed by the scraper's exact source
 * label. Shared portals can therefore serve several employer identities while
 * each company page still links to the correct official board.
 */
export const COMPANY_PORTALS: Record<string, string> = {
  'City of Toronto': 'https://jobs.toronto.ca/jobsatcity/',
  'Government of Canada': 'https://www.canada.ca/en/public-service-commission/jobs/services/gc-jobs.html',
  'Province of Ontario': 'https://www.gojobs.gov.on.ca/Jobs.aspx',
  'Province of Ontario (OPS)': 'https://www.gojobs.gov.on.ca/Jobs.aspx',
  'CMHC': 'https://www.cmhc-schl.gc.ca/about-us/careers',
  'University of Toronto': 'https://jobs.utoronto.ca/',
  'Metrolinx': 'https://metrolinx.com/en/about-us/careers',
  'TTC': 'https://www.ttc.ca/careers',
  'VIA Rail Canada': 'https://careers.viarail.ca/search/?locale=en_US&previewLink=true&referrerSave=false',
  'BC Transit': 'https://jobs.bctransit.com/search/',
  'TransLink': 'https://www.translink.ca/about-us/careers',
  'Waterfront Toronto': 'https://www.waterfrontoronto.ca/about-us/careers',
  'TRCA': 'https://trca.ca/about/careers/',
  'Infrastructure Ontario': 'https://www.infrastructureontario.ca/en/careers/',
  'CreateTO': 'https://createtg.ca/careers/',
  'City of Hamilton': 'https://www.hamilton.ca/city-careers',
  'City of Barrie': 'https://www.barrie.ca/government-contact/careers',
  'City of Oshawa': 'https://cityofoshawa.njoyn.com/CL/xweb/Xweb.asp?page=joblisting&CLID=126638',
  'Town of Ajax': 'https://ajax.wd10.myworkdayjobs.com/Ajax',
  'Town of Caledon': 'https://recruiting.ultipro.ca/COR5003CALED/JobBoard/55e2803a-385b-47b1-b911-51dd7ed81d1e/',
  'City of Niagara Falls': 'https://niagarafalls.wd10.myworkdayjobs.com/CNF',
  'City of London': 'https://careers.london.ca/search/',
  'City of Kitchener': 'https://jobs.kitchener.ca/search/',
  'City of Waterloo': 'https://cityofwaterloo.talentpoolbuilder.com/',
  'Town of Milton': 'https://www.milton.ca/en/work-and-play/careers.aspx',
  'Town of Oakville': 'https://www.oakville.ca/town-hall/careers/',
  'City of Peterborough': 'https://www.peterborough.ca/en/city-hall/careers.aspx',
  'City of Cambridge': 'https://www.cambridge.ca/en/your-government/careers.aspx',
  'Conservation Halton': 'https://www.conservationhalton.ca/careers/',
  'Municipality of Clarington': 'https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=09ed440f-e109-4f6c-ac03-075ea0a3a5e5&ccId=19000101_000001&lang=en_CA',
  'Town of Whitby': 'https://whitby.wd10.myworkdayjobs.com/EXT',
  'York Region': 'https://york.hua.hrsmart.com/hr/ats/JobSearch/viewAll',
  'City of Markham': 'https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=04bf51f8-d2dd-4641-ba92-183522f6e8b3&ccId=19000101_000001&type=MP&lang=en_CA',
  'Town of Aurora': 'https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=b1fead40-7a8c-4b14-87a0-dc031bab192d&ccId=19000101_000001&lang=en_CA',
  'City of Richmond Hill': 'https://jobs.richmondhill.ca/search/',
  'Peel Region': 'https://careers-peelregion.icims.com/jobs/search?ss=1',
  'City of Guelph': 'https://careers-guelph.icims.com/jobs/search?ss=1',
  'City of Victoria': 'https://careersen-victoria.icims.com/jobs/search?ss=1',
  'Halton Region': 'https://careers.halton.ca/search/',
  'City of Burlington': 'https://wd10.myworkdaysite.com/recruiting/cityofburlington/cob',
  'Mississauga': 'https://jobs.mississauga.ca/search/',
  'City of Brampton': 'https://careers.brampton.ca/search/',
  'City of Vaughan': 'https://cityofvaughan.njoyn.com/cl4/xweb/Xweb.asp?page=joblisting&CLID=74035',
  'City of St. Catharines': 'https://tre.tbe.taleo.net/tre01/ats/careers/v2/searchResults?org=COSC&cws=37',
  'City of Welland': 'https://welland.myavanti.ca/careers',
  'City of Brantford': 'https://www.brantford.ca/en/your-government/careers.aspx',
  'City of Windsor': 'https://cityofwindsor.applytojob.com/apply/',
  'City of Sarnia': 'https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=9ba4d624-1cab-4482-861f-900704c3df0d&ccId=19000101_000001&lang=en_CA',
  'City of St. Thomas': 'https://jobs.dayforcehcm.com/en-CA/stthomas/CANDIDATEPORTAL',
  'Town of Orangeville': 'https://jobs.dayforcehcm.com/en-US/orangeville/CANDIDATEPORTAL',
  'Region of Waterloo': 'https://careers.regionofwaterloo.ca/RoW/search/',
  'City of Thunder Bay': 'https://careers.thunderbay.ca/careers-home/jobs',
  'City of Ottawa': 'https://career47.sapsf.com/careers/cityofottawa/search',
  'City of Kingston': 'https://careers.cityofkingston.ca/CL2/xweb/xweb.asp?CLID=61577&page=joblisting&lang=1',
  'City of Belleville': 'https://cityofbelleville.applytojob.com/apply/',
  'City of Cornwall': 'https://atlas.workland.com/careers/cornwall/jobs?page=1',
  'Town of Smiths Falls': 'https://www.smithsfalls.ca/en/town-hall/careers.aspx',
  'University of Waterloo': 'https://uwaterloo.wd3.myworkdayjobs.com/uw_careers',
  'Brock University': 'https://brocku.wd3.myworkdayjobs.com/brocku_careers',
  'UBC': 'https://ubc.wd10.myworkdayjobs.com/ubcstaffjobs',
  'Sheridan College': 'https://sheridan.njoyn.com/CL3/xweb/xweb.asp?page=joblisting&CLID=55117',
  'Seneca College': 'https://www.senecacollege.ca/about/careers.html',
  'University of Guelph': 'https://careers.uoguelph.ca/search/',
  'University of Ottawa': 'https://uottawa.wd3.myworkdayjobs.com/en-US/uOttawa_External_Career_Site',
  'Algonquin College': 'https://algonquincollege.wd3.myworkdayjobs.com/CareerOpportunities',
  'Fanshawe College': 'https://fanshawec.wd3.myworkdayjobs.com/fanshawecareers',
  'Carleton University': 'https://carleton.njoyn.com/CL2/xweb/xweb.asp?CLID=53443&page=joblisting&lang=1',
  'OCAD University': 'https://tre.tbe.taleo.net/tre01/ats/careers/v2/searchResults?org=OCADU&cws=37',
  'Humber College': 'https://humber.taleo.net/careersection/hbr_ex/jobsearch.ftl?lang=en',
  "Queen's University": 'https://queensu.njoyn.com/cl4/xweb/xweb.asp?page=joblisting&CLID=74827',
  'George Brown College': 'https://georgebrown.csod.com/ux/ats/careersite/4/home?c=georgebrown&lang=en-US',
  'Mohawk College': 'https://talent-mohawkcollege.csod.com/ux/ats/careersite/2/home?c=talent-mohawkcollege',
  'Durham College': 'https://durham.csod.com/ux/ats/careersite/4/home?c=durham',
  'Ontario Tech University': 'https://ontariotechu.csod.com/ux/ats/careersite/4/home?c=ontariotechu',
  'York University': 'https://jobs-ca.technomedia.com/yorkuniversity/',
  'University of Windsor': 'https://efhc.fa.ca2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?mode=location',
  'City of Vancouver': 'https://jobs.vancouver.ca/search/',
  'City of Brandon': 'https://jobs.dayforcehcm.com/brandon/COB',
  'City of Red Deer': 'https://fa-eyjj-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?mode=location',
  'Northumberland County': 'https://www.northumberland.ca/en/county-government/careers.aspx',
  'Toronto District School Board': 'https://www.tdsb.on.ca/About-Us/Employment',
  'City of Winnipeg': 'https://careers.winnipeg.ca/psc/cgext/EMPLOYEE/HRMS/c/HRS_HRAM_FL.HRS_CG_SEARCH_FL.GBL?Page=HRS_APP_SCHJOB_FL&Action=U',
  'Vaughan Public Library': 'https://www.vaughanpl.info/about/careers',
  'London Public Library': 'https://www.lpl.ca/about-us/jobs-library',
  'Richmond Public Library': 'https://www.yourlibrary.ca/careers-at-rpl/',
  'Edmonton Public Library': 'https://www.epl.ca/careers/',
  'Pickering Public Library': 'https://www.pickering.ca/council-city-administration/employment-opportunities/',
  'Durham Region': 'https://www.durham.ca/en/doing-business/careers.aspx',
  'Town of Halton Hills': 'https://www.haltonhills.ca/en/your-government/careers.aspx',
};

export function companyPortal(name: string): string | null {
  return COMPANY_PORTALS[name] ?? null;
}
