export const COMPANY_TYPE_OPTIONS = [
  { value: 'library', label: 'Public libraries' },
  { value: 'transit', label: 'Transit agencies' },
  { value: 'higherEducation', label: 'Universities and colleges' },
  { value: 'municipal', label: 'Municipal governments' },
  { value: 'publicAgency', label: 'Public agencies' },
  { value: 'health', label: 'Health organizations' },
] as const;

export type CompanyType = typeof COMPANY_TYPE_OPTIONS[number]['value'];

// This is keyed by the scraper's exact source label. It is deliberately not
// inferred from words in company names, so an organization can have more than
// one stable type without changing when a name happens to contain "City" or
// "University".
export const COMPANY_TYPES: Record<string, CompanyType[]> = {
  'Government of Canada': ['publicAgency'],
  'Province of Ontario (OPS)': ['publicAgency'],
  'CMHC': ['publicAgency'],
  'Metrolinx': ['publicAgency', 'transit'],
  'TRCA': ['publicAgency'],
  'Infrastructure Ontario': ['publicAgency'],
  'CreateTO': ['publicAgency'],
  'Conservation Halton': ['publicAgency'],
  'Waterfront Toronto': ['publicAgency'],
  'TTC': ['transit', 'publicAgency'],
  'EFHC': ['higherEducation'],
  'Toronto District School Board': ['publicAgency'],
  'City of Barrie': ['municipal'],
  'City of Belleville': ['municipal'],
  'City of Brampton': ['municipal'],
  'City of Brantford': ['municipal'],
  'City of Brandon': ['municipal'],
  'City of Burlington': ['municipal'],
  'City of Cambridge': ['municipal'],
  'City of Cornwall': ['municipal'],
  'City of Guelph': ['municipal'],
  'City of Hamilton': ['municipal'],
  'City of Kitchener': ['municipal'],
  'City of Kingston': ['municipal'],
  'City of London': ['municipal'],
  'City of Markham': ['municipal'],
  'City of Niagara Falls': ['municipal'],
  'City of Oshawa': ['municipal'],
  'City of Peterborough': ['municipal'],
  'City of Richmond Hill': ['municipal'],
  'City of Sarnia': ['municipal'],
  'City of St. Catharines': ['municipal'],
  'City of St. Thomas': ['municipal'],
  'City of Thunder Bay': ['municipal'],
  'City of Toronto': ['municipal'],
  'City of Vancouver': ['municipal'],
  'City of Victoria': ['municipal'],
  'City of Vaughan': ['municipal'],
  'City of Waterloo': ['municipal'],
  'City of Welland': ['municipal'],
  'City of Windsor': ['municipal'],
  'City of Winnipeg': ['municipal'],
  'City of Ajax': ['municipal'],
  'Town of Ajax': ['municipal'],
  'Town of Aurora': ['municipal'],
  'Town of Caledon': ['municipal'],
  'Town of Milton': ['municipal'],
  'Town of Oakville': ['municipal'],
  'Town of Orangeville': ['municipal'],
  'Town of Smiths Falls': ['municipal'],
  'Town of Whitby': ['municipal'],
  'Municipality of Clarington': ['municipal'],
  'Northumberland County': ['municipal'],
  'Peel Region': ['municipal'],
  'Halton Region': ['municipal'],
  'Niagara Region': ['municipal'],
  'Region of Waterloo': ['municipal'],
  'York Region': ['municipal'],
  'University of Guelph': ['higherEducation'],
  'University of Ottawa': ['higherEducation'],
  'University of Toronto': ['higherEducation'],
  'University of Waterloo': ['higherEducation'],
  'Algonquin College': ['higherEducation'],
  'Brock University': ['higherEducation'],
  'Carleton University': ['higherEducation'],
  'Centennial College': ['higherEducation'],
  'Durham College': ['higherEducation'],
  'Fanshawe College': ['higherEducation'],
  'George Brown College': ['higherEducation'],
  'Humber College': ['higherEducation'],
  'Mohawk College': ['higherEducation'],
  'OCAD University': ['higherEducation'],
  'Ontario Tech University': ['higherEducation'],
  "Queen's University": ['higherEducation'],
  'Seneca College': ['higherEducation'],
  'Sheridan College': ['higherEducation'],
  'Vaughan Public Library': ['library'],
  'Edmonton Public Library': ['library'],
  'London Public Library': ['library'],
  'Oakville Public Library': ['library'],
  'Richmond Public Library': ['library'],
  'Ontario Health': ['health', 'publicAgency'],
  'Ontario Health atHome': ['health', 'publicAgency'],
  'Public Health Ontario': ['health', 'publicAgency'],
  'Shared Health Manitoba': ['health', 'publicAgency'],
  'Manitoba Public Insurance': ['publicAgency'],
};

export function companyTypes(name: string): CompanyType[] {
  return COMPANY_TYPES[name] ?? [];
}
